name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -T -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Clone the repository if not already present
            if [ ! -d "your-repo" ]; then
              git clone https://github.com/VootlaSaiCharan/htmlproject.git
            fi

            cd htmlproject
            git pull origin master

            # Build Docker image
            docker build -t my-nginx-app .

            # Stop and remove existing container if it exists
            docker stop my-nginx-app || true
            docker rm my-nginx-app || true

            # Run the new container
            docker run -d -p 80:80 --name my-nginx-app my-nginx-app:latest
          EOF